# Generated by Django 4.2.18 on 2025-02-08 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Filter', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='address',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
