# Generated by Django 4.2.18 on 2025-02-09 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Filter', '0002_user_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='address',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
